### ISSUE TITLE
Fix mysql support

### ISSUE THREAD

**Issue by 0xIO32** [KekOnTheWorld/uploadserver#29]
thread 'main' panicked at 'Failed to create pool: Error(Some("missing \"=\" after \"mysql://\<username\>:\<pwd\>@\<host\>/\<database\>\" in connection info string\n"))', src/database.rs:20:30
stack backtrace:
   0:     0x55d02e29f681 - std::backtrace_rs::backtrace::libunwind::trace::h8bc3e596fd6e6181
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55d02e29f681 - std::backtrace_rs::backtrace::trace_unsynchronized::h9a0656fedca2f962
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d02e29f681 - std::sys_common::backtrace::_print_fmt::h11ca79bc953fda0e
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55d02e29f681 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h23585af82c540d61
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55d02e2c539f - core::fmt::rt::Argument::fmt::h1e7f4bcecbee3fbb
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/core/src/fmt/rt.rs:138:9
   5:     0x55d02e2c539f - core::fmt::write::h41633f265152b738
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/core/src/fmt/mod.rs:1094:21
   6:     0x55d02e29c467 - std::io::Write::write_fmt::hdf9fdeebf4391d4c
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/io/mod.rs:1714:15
   7:     0x55d02e29f495 - std::sys_common::backtrace::_print::h0761f433dadea582
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55d02e29f495 - std::sys_common::backtrace::print::hffcd468cc9baf957
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55d02e2a0993 - std::panicking::default_hook::{{closure}}::h70eb212f41458c90
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/panicking.rs:269:22
  10:     0x55d02e2a0724 - std::panicking::default_hook::hf217f8886a1385fc
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/panicking.rs:288:9
  11:     0x55d02e2a0f19 - std::panicking::rust_panic_with_hook::h7901b0073bb3ed74
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/panicking.rs:705:13
  12:     0x55d02e2a0e17 - std::panicking::begin_panic_handler::{{closure}}::hec74e56b1f659f1d
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/panicking.rs:597:13
  13:     0x55d02e29fab6 - std::sys_common::backtrace::__rust_end_short_backtrace::hb5aad058838135df
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/sys_common/backtrace.rs:151:18
  14:     0x55d02e2a0b62 - rust_begin_unwind
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/panicking.rs:593:5
  15:     0x55d02dfea153 - core::panicking::panic_fmt::h837c4ca50a3367f6
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/core/src/panicking.rs:67:14
  16:     0x55d02dfea5f3 - core::result::unwrap_failed::h7504eec236fd53d7
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/core/src/result.rs:1651:5
  17:     0x55d02e057e30 - uploadserver::database::establish_connection::hbab22dcbcbd93c30
  18:     0x55d02e0984fe - tokio::runtime::park::CachedParkThread::block_on::hf71997c369343a99
  19:     0x55d02e099bba - tokio::runtime::context::runtime::enter_runtime::hfe659ab293c49133
  20:     0x55d02e020302 - uploadserver::main::h23c80956f20fcb35
  21:     0x55d02e0723a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hfcf2860405d9c9ce
  22:     0x55d02e05d6e9 - std::rt::lang_start::{{closure}}::h754760404b90abfe
  23:     0x55d02e2983db - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hcc4883d946dcf138
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/core/src/ops/function.rs:284:13
  24:     0x55d02e2983db - std::panicking::try::do_call::h77829f7a7f88de13
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/panicking.rs:500:40
  25:     0x55d02e2983db - std::panicking::try::h0dc439302435d6b7
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/panicking.rs:464:19
  26:     0x55d02e2983db - std::panic::catch_unwind::hf651274712a93429
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/panic.rs:142:14
  27:     0x55d02e2983db - std::rt::lang_start_internal::{{closure}}::h251a3b7a6f2ffec7
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/rt.rs:148:48
  28:     0x55d02e2983db - std::panicking::try::do_call::h5ffc5679741c54c6
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/panicking.rs:500:40
  29:     0x55d02e2983db - std::panicking::try::hbd5c63ffc844d2d0
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/panicking.rs:464:19
  30:     0x55d02e2983db - std::panic::catch_unwind::h12025ab3508dacbd
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/panic.rs:142:14
  31:     0x55d02e2983db - std::rt::lang_start_internal::h6e2a2aca03688ff4
                               at /rustc/5bd28f5eac1ba3569bfa8d49ec3f5acbdfdff7a0/library/std/src/rt.rs:148:20
  32:     0x55d02e0204e5 - main
  33:     0x7f50d71d3a90 - <unknown>
  34:     0x7f50d71d3b49 - __libc_start_main
  35:     0x55d02dfea8ba - _start
  36:                0x0 - <unknown>

docker-compose.yml
```
version: '3'
services:
  uploadserver:
    image: uploadserver:latest
    container_name: uploadserver
    environment:
    - tmp_dir=/tmp
    - upload_dir=/upload
    - web_dir=/web
    - download_url=https://markustieger.synology.me:4040
    - DATABASE_URL=mysql://<user>:<pwd>@<host>/<database>
    - RUST_BACKTRACE=full

    networks:
      reverse_proxy:
        ipv4_address: '172.40.0.8'

networks:
  reverse_proxy:
    name: reverse-proxy
    external: true
```

(ja ich habe \<user\> etc. ausgetauscht, mit den daten)

Getested mit dem prebuilt und mit selbst compilten.

**Comment by lbirkert** [comment]
kekupload-server does **not** currently work with mysql. Setup a PostgreSQL Database instead.
